version: "2"
linters:
  default: all
  disable:
    - err113
    - mnd
    - cyclop
    - dupl
    - exhaustruct
    - forbidigo
    - funlen
    - gocognit
    - gosec
    - govet
    - nlreturn
    - paralleltest
    - wrapcheck
    - wsl
    - tagliatelle
    - testpackage
    - varnamelen
    - depguard
    - ireturn
  settings:
    lll:
      line-length: 120
    revive:
      rules:
        - name: empty-block
          disabled: true
    tagliatelle:
      case:
        use-field-name: true
        rules:
          json: snake
  exclusions:
    rules:
      - path: cmd/robinhood-export/main.go
        linters:
          - gochecknoglobals
formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/vitoordaz/robinhood-export
