name: Linter
on: 
  push: 
    branches: [mainline]
jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21'
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with: 
          version: latest