name: Test
on: 
  push: 
    branches: [mainline]
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21'
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Test
        run: go test -timeout 1h -v ./...